### ISSUE TITLE
[BUG] Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while connecting

### ISSUE THREAD

**Issue by rogerfan03** [alexyakunin/BoardGames#4]
What I did to try and fix this:
Edited app_release's settings to be like this
[docker_out.log](https://github.com/alexyakunin/BoardGames/files/6128176/docker_out.log)

```yaml
    ports:
     - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://*:8080"
      HTTPS_PORT: 4430
```

`docker compose down && docker compose up --build app_release`

I checked via `sudo lsof -i -P -n | grep :5432`,  `sudo lsof -i -P -n | grep :8080`  and `sudo lsof -i -P -n | grep :4430` that the ports are not already in use.

The full log is attached.
FYI: I'm running this on an Quasi-Ubuntu VM (Pop OS Virtualbox), docker by itself seems to work, tested by successful run of `docker run hello-world`.
The same exact issue also occurs when trying to run app_debug instead of app_release.
